// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    account_name
) VALUES (
    $1
) RETURNING account_id
`

func (q *Queries) CreateAccount(ctx context.Context, accountName pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, createAccount, accountName)
	var account_id int32
	err := row.Scan(&account_id)
	return account_id, err
}

const createColDefConfig = `-- name: CreateColDefConfig :one
INSERT INTO column_def_config (
    account_id, col_def_config
) VALUES (
    $1, $2
) RETURNING  account_id
`

type CreateColDefConfigParams struct {
	AccountID    int32
	ColDefConfig []byte
}

func (q *Queries) CreateColDefConfig(ctx context.Context, arg CreateColDefConfigParams) (int32, error) {
	row := q.db.QueryRow(ctx, createColDefConfig, arg.AccountID, arg.ColDefConfig)
	var account_id int32
	err := row.Scan(&account_id)
	return account_id, err
}

const createSierraData = `-- name: CreateSierraData :one
INSERT INTO sierra_data (
    account_id, symbol, entry_datetime, trade_type, duration, profit_loss, cumulative_profit_loss,
    max_open_profit, max_open_loss, exit_datetime, commission, max_open_quantity, trade_quantity, entry_price,
    exit_price, max_closed_quantity, flat_to_flat_profit_loss, flat_to_flat_max_open_profit, flat_to_flat_max_open_loss,
    entry_efficiency, total_efficiency, high_price_while_open, low_price_while_open, note, open_position_quantity,
    close_position_quantity
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22,
    $23, $24, $25, $26
) RETURNING sierra_data_id
`

type CreateSierraDataParams struct {
	AccountID               pgtype.Int4
	Symbol                  pgtype.Text
	EntryDatetime           pgtype.Timestamp
	TradeType               pgtype.Text
	Duration                pgtype.Text
	ProfitLoss              pgtype.Numeric
	CumulativeProfitLoss    pgtype.Numeric
	MaxOpenProfit           pgtype.Numeric
	MaxOpenLoss             pgtype.Numeric
	ExitDatetime            pgtype.Timestamp
	Commission              pgtype.Numeric
	MaxOpenQuantity         pgtype.Int4
	TradeQuantity           pgtype.Int4
	EntryPrice              pgtype.Numeric
	ExitPrice               pgtype.Numeric
	MaxClosedQuantity       pgtype.Int4
	FlatToFlatProfitLoss    pgtype.Numeric
	FlatToFlatMaxOpenProfit pgtype.Numeric
	FlatToFlatMaxOpenLoss   pgtype.Numeric
	EntryEfficiency         pgtype.Numeric
	TotalEfficiency         pgtype.Numeric
	HighPriceWhileOpen      pgtype.Numeric
	LowPriceWhileOpen       pgtype.Numeric
	Note                    pgtype.Text
	OpenPositionQuantity    pgtype.Int4
	ClosePositionQuantity   pgtype.Int4
}

func (q *Queries) CreateSierraData(ctx context.Context, arg CreateSierraDataParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSierraData,
		arg.AccountID,
		arg.Symbol,
		arg.EntryDatetime,
		arg.TradeType,
		arg.Duration,
		arg.ProfitLoss,
		arg.CumulativeProfitLoss,
		arg.MaxOpenProfit,
		arg.MaxOpenLoss,
		arg.ExitDatetime,
		arg.Commission,
		arg.MaxOpenQuantity,
		arg.TradeQuantity,
		arg.EntryPrice,
		arg.ExitPrice,
		arg.MaxClosedQuantity,
		arg.FlatToFlatProfitLoss,
		arg.FlatToFlatMaxOpenProfit,
		arg.FlatToFlatMaxOpenLoss,
		arg.EntryEfficiency,
		arg.TotalEfficiency,
		arg.HighPriceWhileOpen,
		arg.LowPriceWhileOpen,
		arg.Note,
		arg.OpenPositionQuantity,
		arg.ClosePositionQuantity,
	)
	var sierra_data_id int32
	err := row.Scan(&sierra_data_id)
	return sierra_data_id, err
}

const createSierraDataTags = `-- name: CreateSierraDataTags :one
INSERT INTO sierra_data_tags (
    sierra_data_id, tag_def_id, tag_value
) VALUES (
    $1, $2, $3
) RETURNING sierra_data_tag_id
`

type CreateSierraDataTagsParams struct {
	SierraDataID pgtype.Int4
	TagDefID     pgtype.Int4
	TagValue     pgtype.Text
}

func (q *Queries) CreateSierraDataTags(ctx context.Context, arg CreateSierraDataTagsParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSierraDataTags, arg.SierraDataID, arg.TagDefID, arg.TagValue)
	var sierra_data_tag_id int32
	err := row.Scan(&sierra_data_tag_id)
	return sierra_data_tag_id, err
}

const createTagDefConfig = `-- name: CreateTagDefConfig :one
INSERT INTO tag_def_config (
    account_id, tag_def_config
) VALUES (
    $1, $2
) RETURNING account_id
`

type CreateTagDefConfigParams struct {
	AccountID    int32
	TagDefConfig []byte
}

func (q *Queries) CreateTagDefConfig(ctx context.Context, arg CreateTagDefConfigParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTagDefConfig, arg.AccountID, arg.TagDefConfig)
	var account_id int32
	err := row.Scan(&account_id)
	return account_id, err
}

const createTagDefs = `-- name: CreateTagDefs :one
INSERT INTO tag_defs (
    account_id, tag_name
) VALUES (
    $1, $2
) RETURNING tag_def_id
`

type CreateTagDefsParams struct {
	AccountID pgtype.Int4
	TagName   pgtype.Text
}

func (q *Queries) CreateTagDefs(ctx context.Context, arg CreateTagDefsParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTagDefs, arg.AccountID, arg.TagName)
	var tag_def_id int32
	err := row.Scan(&tag_def_id)
	return tag_def_id, err
}
